# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bytes_extra.proto
# Protobuf Python Version: 4.25.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x62ytes_extra.proto\"\xb8\x01\n\nBytesExtra\x12#\n\x05\x66lags\x18\x01 \x03(\x0b\x32\x14.BytesExtra.FlagAttr\x12\'\n\x07strings\x18\x03 \x03(\x0b\x32\x16.BytesExtra.StringAttr\x1a,\n\x08\x46lagAttr\x12\x11\n\tenum_code\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x03\x1a.\n\nStringAttr\x12\x11\n\tenum_code\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bytes_extra_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BYTESEXTRA']._serialized_start=22
  _globals['_BYTESEXTRA']._serialized_end=206
  _globals['_BYTESEXTRA_FLAGATTR']._serialized_start=114
  _globals['_BYTESEXTRA_FLAGATTR']._serialized_end=158
  _globals['_BYTESEXTRA_STRINGATTR']._serialized_start=160
  _globals['_BYTESEXTRA_STRINGATTR']._serialized_end=206
# @@protoc_insertion_point(module_scope)
